services:
  db:
    image: mysql:8.4
    container_name: media-server-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"

  redis:
    image: redis:latest
    container_name: media-server-redis
    restart: unless-stopped
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data

  app-dev:
    build:
      context: .
      dockerfile: ./docker/app-dev/Dockerfile
    container_name: media-server-app-dev
    restart: unless-stopped
    command: sleep infinity
    env_file:
      - .env
    volumes:
      - ${HOST_MEDIA_ROOT}:/media:rw
    ports:
      - "13000:3000"
    depends_on:
      - db
      - redis
    profiles:
      - dev

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: runner
    container_name: media-server-app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${HOST_MEDIA_ROOT}:/media:rw
    ports:
      - "13001:3000"
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: worker
    container_name: media-server-worker
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${HOST_MEDIA_ROOT}:/media:rw
    depends_on:
      - redis

  migration:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: migration
    container_name: media-server-migration
    restart: no
    env_file:
      - .env
    depends_on:
      - db

  caddy:
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
    container_name: media-server-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - app
    profiles:
      - public

volumes:
  db_data:
  redis_data:
  caddy_data:
