services:
  db:
    image: mysql:8.0
    container_name: media-server-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: media-server-app
    restart: unless-stopped
    command: sleep infinity
    env_file:
      - .env
    volumes:
      - D:\media:/media:rw
    ports:
      - "3001:3000"
    depends_on:
      - db

volumes:
  db_data:
