services:
  db:
    image: mysql:8.0
    command: --wait_timeout=60 --interactive_timeout=60
    container_name: media-server-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"

  app-dev:
    build:
      context: .
      dockerfile: ./docker/app-dev/Dockerfile
    container_name: media-server-app-dev
    restart: unless-stopped
    command: sleep infinity
    env_file:
      - .env
    volumes:
      - ${HOST_MEDIA_ROOT}:/media:rw
    ports:
      - "13000:3000"
    depends_on:
      - db
    profiles:
      - dev

  app-dev-runner:
    build:
      context: .
      dockerfile: ./docker/app-dev/Dockerfile
    container_name: media-server-app-dev-runner
    restart: unless-stopped
    command: sh -c "pnpm prisma generate && pnpm build && pnpm start"
    env_file:
      - .env
    volumes:
      - ${HOST_MEDIA_ROOT}:/media:rw
    ports:
      - "13002:3000"
    depends_on:
      - db
    profiles:
      - dev-runner

  app-prod:
    build:
      context: .
      dockerfile: ./docker/app-prod/Dockerfile
      target: runner
    container_name: media-server-app-prod
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${HOST_MEDIA_ROOT}:/media:rw
    ports:
      - "13001:3000"
    depends_on:
      - db
    profiles:
      - prod

volumes:
  db_data:
